### ISSUE TITLE
Mac compatibility problems 1 : ctypes on non windows env

### ISSUE THREAD

**Issue by Bruyant** [CEMES-CNRS/PyMoDAQ#1]
when starting pymodaq from pip using daq_scan, the import of "daq_utils.py" fail on 
`ImportError: cannot import name 'WINFUNCTYPE' from 'ctypes' (/Users/nicolasbruyant/anaconda3/lib/python3.7/ctypes/__init__.py`

**Comment by seb5g** [comment]
Release 1.4.2 takes care of that issue

**Comment by Bruyant** [comment]
I tried GitHub version but no change:
proposed fix:
```
if os.name == 'posix':
    # TODO find equivalent code for linux and mac
    print("OS not fully supported: TODO add code for linux and mac")
if os.name == 'nt': # specific for windows
    from ctypes import CFUNCTYPE, WINFUNCTYPE    
else: 
    print("OS not fully supported")
```

**Comment by seb5g** [comment]
darwin answer to sys.platform is a cause of subsequent problems. Master release is now fine pip release 1.4.2 is now fine.
I prefer to use sys.platform so compared it to win32 for the winfunctype import  :

System | platform value
-- | --
Linux | 'linux'
Windows | 'win32'
Windows/Cygwin | 'cygwin'
Mac OS X | 'darwin'
