### ISSUE TITLE
Data view axes with h5browser

### ISSUE THREAD

**Issue by quantumm** [CEMES-CNRS/PyMoDAQ#13]
To test the functionalities of pymodaq (1.6.2) I have performed 1D scans with a SmarAct actuator and a function generator plugged on a Lecroy oscilloscope (DAQ 1D viewer). The two are decoupled so of course the oscilloscope acquisition will not change with the position of the actuator.
Here is what the reading of the oscilloscope looks like:
![ScopeTrace](https://user-images.githubusercontent.com/5221986/66119297-ad9db000-e5d8-11e9-9615-de116e44c782.PNG)

And here is what a scan looks like:
![Scan1D](https://user-images.githubusercontent.com/5221986/66119353-c6a66100-e5d8-11e9-907e-b48c0ef08a23.PNG)

### 1
As I understand the bottom axis is the number of steps of the scan (40 which is correct), and the top axis gives the position of the scan (from -12 to -8µ : ok).
What would be nice is to get the same on the y axis. I suppose that 20000 is the number of samples on the scope time axis but the correspondance is not given directly on this view.

### 2
If I clic the button ’Rotate the image by 90°’ I get this
![Scan1D_rotated90degrees](https://user-images.githubusercontent.com/5221986/66120268-c7d88d80-e5da-11e9-87f9-04f5c59df6f9.PNG)

The image is rotated but the axes seem not to follow and it makes no sense.

**Comment by seb5g** [comment]
To be clear, you are speaking about the '2D plot' viewer within the DAQ_Scan module, right?
In the next push, I will add the vertical axis scaling, label and unit information.
Rotating the image here doen't mean  anything, this functionnality is just to be used to rotate data from a camera. To avoid any misunderstanding, in the next push the corresponding icons will be hidden

**Comment by seb5g** [comment]
Done

**Comment by quantumm** [comment]
Those images are taken from the h5browser module, not from the DAQ_Scan module.

**Comment by seb5g** [comment]
It doesnt make sense, in the h5 browser a 1d scan of 1d data should not
look like this.  Could you add a snapshot of the h5browser window?

**Comment by quantumm** [comment]
Sure
![h5browser](https://user-images.githubusercontent.com/5221986/66225138-f8522180-e6d7-11e9-9853-51571ff1f151.PNG)

**Comment by seb5g** [comment]
Oh I See, you're talking about live data. .. i'll have a look into it!
