### ISSUE TITLE
h5browser with version 1.6.3

### ISSUE THREAD

**Issue by quantumm** [CEMES-CNRS/PyMoDAQ#15]
I tested the h5browser with the new version 1.6.3. The data is acquired with this version.
It seems that the problem with the logger is solved:
![Capture du 2019-10-23 17-11-45](https://user-images.githubusercontent.com/5221986/67408974-2aa9bd00-f5ba-11e9-903e-a61cb34eadfa.png)

I can also see the data from the scope at any position of the stage, this seems ok.
![Capture du 2019-10-23 17-16-45](https://user-images.githubusercontent.com/5221986/67409267-9e4bca00-f5ba-11e9-9e5b-120eb3842284.png)

However I am surprised that there is no Live_scan_1D node anymore: so I cannot get the complete image of the scan in one picture anymore: the scope reading as a function of the position of the stage. This was ok in the previous version.

Some other remarks:
- I do not get the meaning of the axis of the view when I am on the Ch000/X_axis node:
![Capture du 2019-10-23 17-40-16](https://user-images.githubusercontent.com/5221986/67410613-a573d780-f5bc-11e9-878f-f8a7f36251ca.png)
Is it supposed to be the position of the stage depending on the acquisition time/step ?

- Same when I am on the Scan_x_axis node:
![Capture du 2019-10-23 17-40-37](https://user-images.githubusercontent.com/5221986/67410681-c0464c00-f5bc-11e9-87f4-239123f4ce84.png)

- If I double-clic on the ScanXXX node, it happens that the program crash.

**Comment by seb5g** [comment]
the X_axis node below the Data Node corresponds to the X_axis from your detector (so the time axis of the scope in your case)!

The Scan_x_axis is the axis of the actuator during the scan. You've scanned between -10 and +10

Finally the 1.6.3 is quite buggy due to some new features in the axis labelling, the github repo has already quite a few commits correcting for them. A version 1.6.4 is soon to come when most of the bugs will be cleared! For the time beoing please use the uptodate code from github

**Comment by quantumm** [comment]
- X_axis node below the Data Node: Ok I understand now ! So this is fine. Maybe the labelling 'sample' could be more appropriate than 'pixel'.
- Scan_x_axis: Ok I got it. Then maybe the label should be 'step'.

Sorry to insist so much with those labellings :P, but at first sight it is not so easy to get the meaning of this tree architecture so I hope it could help.

I would keep the issue opened to remind us the problem of the Live_scan_1D node.

Thanks !

**Comment by seb5g** [comment]
Well in case of a camera 'pixel' is more accurate. That being said, you may export from your plugin any kind of label and unit for your axis (see http://pymodaq.cnrs.fr/usage/modules/Plugins.html#emission-of-data)

I'll look into it for hte Scan_x_axis case

Did you try the last github version of the code, to see if the live data problem is still happening?

**Comment by quantumm** [comment]
I agree that 'pixel' is fine for the detector, but 'pixel' for a scan step ?


Now I tested the last github version:

- The double-clic bug on the ScanXXX node bug is solved
- Everything concerning the Detector000 node and below seems fine
- The Live_scan_1D node is back, but still has a strange behavior:
A tiny picture is appearing on top of the 'parameters' column:
![Capture du 2019-10-24 15-10-35](https://user-images.githubusercontent.com/5221986/67503133-62cb0180-f687-11e9-82bb-d23865ce15fa.png)
All the subnodes seem ok but the 'Data' one. If I double-clic on it nothing happens: 
![Capture du 2019-10-24 17-50-10](https://user-images.githubusercontent.com/5221986/67503370-d0772d80-f687-11e9-9dc3-17174af550a7.png)

**Comment by seb5g** [comment]
All resolved in latest releases
