### ISSUE TITLE
Mac compatibility problems 1 : bug in platform test

### ISSUE THREAD

**Issue by Bruyant** [CEMES-CNRS/PyMoDAQ#2]
On mac (i.e. Darwin system ..) load fail on 
```
  File "/Users/nicolasbruyant/anaconda3/lib/python3.7/site-packages/pymodaq/daq_utils/daq_utils.py", line 180, in get_set_local_dir
    local_path = os.path.join(os.environ['HOMEDRIVE'] + os.environ['HOMEPATH'], 'pymodaq_local')
```

because the test ` if 'win' in sys.platform: ` fail because darwin is for the sys.platform answer for Mac.

**Comment by Bruyant** [comment]
proposed fix:
def get_set_local_dir():
    # if 'win' in sys.platform: buggy because darwin is for mac
    if os.name == 'posix':
        local_path = os.path.join(os.environ['PATH'], 'pymodaq_local')
    if os.name == 'nt':
        local_path = os.path.join(os.environ['HOMEDRIVE'] + os.environ['HOMEPATH'], 'pymodaq_local')    
    else:
        print("OS NOT SUPPORTED")

**Comment by seb5g** [comment]
same as #1 now fixed
