### ISSUE TITLE
Externalized configuration

### ISSUE THREAD

**Issue by TheSirC** [CEMES-CNRS/PyMoDAQ#27]
During the training session on October 13th it was found that a lot of the options in the code are hardcoded to values that can not be generalized to other setups.

A quick search through the code yielded this primary results that could be transferred to a configuration manager class :

- [ ] [daq_logger.py](https://github.com/CEMES-CNRS/PyMoDAQ/tree/master/pymodaq/daq_logger.py#L680)

`prog.set_preset_mode('C:\\Users\\weber\\pymodaq_local\\preset_configs\\preset_default.xml')`

- [ ] [daq_scan.py](https://github.com/CEMES-CNRS/PyMoDAQ/tree/master/pymodaq/daq_scan.py#L1935)

`prog.set_preset_mode('C:\\Users\\weber\\pymodaq_local\\preset_configs\\preset_adaptive.xml')`

- [ ] [daq_utils/daq_utils.py](https://github.com/CEMES-CNRS/PyMoDAQ/tree/master/pymodaq/daq_utils/daq_utils.py#L1004)

`get_new_file_name(base_path=Path('C:\Data'), base_name='tttr_data'):`

- [ ] [daq_utils/h5modules.py](https://github.com/CEMES-CNRS/PyMoDAQ/tree/master/pymodaq/daq_utils/h5modules.py#L983)

`{'title': 'Base path:', 'name': 'base_path', 'type': 'browsepath', 'value': 'C:\Data',`

- [ ] [daq_utils/h5modules.py](https://github.com/CEMES-CNRS/PyMoDAQ/tree/master/pymodaq/daq_utils/h5modules.py#L987)

`{'title': 'Current path:', 'name': 'current_scan_path', 'type': 'text', 'value': 'C:\Data',`

- [ ] [daq_utils/gui_utils.py](https://github.com/CEMES-CNRS/PyMoDAQ/tree/master/pymodaq/daq_utils/gui_utils.py#L128)

`select_file(start_path="C:\\test.h5",save=True,ext='h5')`

- [ ] [examples/custom_app.py](https://github.com/CEMES-CNRS/PyMoDAQ/tree/master/pymodaq/examples/custom_app.py#L29)

`{'title': 'Save base path:', 'name': 'base_path', 'type': 'browsepath', 'value': 'C:\Data'},`

- [ ] [daq_analysis/daq_analysis_main.py](https://github.com/CEMES-CNRS/PyMoDAQ/tree/master/pymodaq/daq_analysis/daq_analysis_main.py#L581)

`prog.open_h5_file('C:\\Data\\2018\\20180212\\Dataset_20180212_000\\Dataset_20180212_000.h5')`

- [ ] [daq_utils/tree_layout/tree_layout_main.py](https://github.com/CEMES-CNRS/PyMoDAQ/tree/master/pymodaq/daq_utils/tree_layout/tree_layout_main.py#L167)

`# filename='C:\\Data\\2019\\20190220\\Dataset_20190220_004\\Dataset_20190220_004.h5'`

**Comment by seb5g** [comment]
Starting working on this in the config-file branch

**Comment by seb5g** [comment]
Config file is operational. Using the toml package. At startup, pymodaq check the existence of such a file in pymodaq_local path. If it exists, it uses it, if not it create a new one from the template situated within the project root
to be used and let me know if any other configuration values should be added
