### ISSUE TITLE
Opening access to the wiki

### ISSUE THREAD

**Issue by TheSirC** [CEMES-CNRS/PyMoDAQ#28]
Good on-boarding documentation is key to smooth the welcoming of new users.

Documentation on installation steps exists on the website but to allow quick documentation on commons problems that can occur from different setups a wiki is key to allow users to share their solutions from problems they faced and solved for other users to benefit from their experiences.

A wiki tab exists but is not accessible probably because _no pages were created_ but also because ["Only repository collaborators can edit a public repository's wiki by default, but you can allow anyone with a GitHub account to edit your wiki." --The Github documentation](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/changing-access-permissions-for-wikis).

A quick fix will be to follow [the steps of the documentation cited](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/changing-access-permissions-for-wikis).

**Comment by seb5g** [comment]
Wiki has been opened and a first initial page created. I'm not sure what you thought would be good here as much is on the official documentation: pymodaq.cnrs.fr

**Comment by TheSirC** [comment]
I saw that the wiki could be another way, this time for users, to contribute to documentation in a low-bar way, to document difficulties and solutions they found.  Not a replacement for any existing system.

It is a parallel way to document different experiences : API reference for the official website, troubleshooting tips and general advice for the wiki.

I will be, for my part, adding steps to document my journey for a [Nix script](https://nixos.org) for building pyMoDAQ to improve reproducibility on system using Nix package manager.

**Comment by seb5g** [comment]
Alright but it seems only owners can update the wiki...

**Comment by TheSirC** [comment]
The documentation, cited in the [original post](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/changing-access-permissions-for-wikis), reads (emphasis mine) : "Only repository collaborators can edit a public repository's wiki _by default_, but you can allow anyone with a GitHub account to edit your wiki."

**Comment by seb5g** [comment]
From the repo settings, here it is:

![image](https://user-images.githubusercontent.com/6609955/96305618-768d1780-0ffe-11eb-9bec-3f328bc5802b.png)

So is it editable yet? I cannot check actually! (I did it unsigned but obviously it didn't work)

**Comment by TheSirC** [comment]
[Given the revision I succeed to make](https://github.com/CEMES-CNRS/PyMoDAQ/wiki/Home/_history) the wiki seems functional! :partying_face:
