### ISSUE TITLE
PyQt5 manquant

### ISSUE THREAD

**Issue by clavay** [CEMES-CNRS/PyMoDAQ#3]
Salut,

Je suis sous debian 9 et python 3.5.3.
J'ai installé pymodaq : pip3 install pymodaq
Quand j'essaye de le lancer : python3 -m pymodaq
J'ai l'erreur suivante : ImportError: No module named 'PyQt5'

Je vois que dans setup.py c'est commenté : #'pyqt5'

**Comment by seb5g** [comment]
Salut, Hello,
This forum is meant to be international so please try to use english to post issues!

Utilises-tu une distribution anaconda? Si oui, il faut utiliser conda pour installer pyqt5, le faire manuellement est source de pas mal de problème (d'où le commentaire dans setup.py). 

Pyqt5 is best installed using anaconda or miniconda, you'll have to use conda package manager to install it. That will resolve many issues faced when trying to install it manually!
Hope it helps!

**Comment by clavay** [comment]
Ok for english.
I don't use anaconda.
Only pip to install package.

**Comment by seb5g** [comment]
well try to install pyqt5 using pip but usually it won't work as simply. That's why it is recomended to use anaconda (or miniconda, that I use) or even winpython on windows. Then package installation is much easier!

**Comment by clavay** [comment]
I solved it with :
pip3 install pyqt5 numba scipy matplolib
Without using anaconda, only pip. Now I will try to use PyMoDaq.

**Comment by looninho** [comment]
Hi seb5g,

After install pymodaq with pip, I launch pymodad module like this "Scripts\pymodaq_scan" but nothing happens, just the windows timer cursor appears for 1second with no error or warning msg.

I use Anaconda (Windows 10) and I create an env "DAQ" where I execute the previous cmd.

I also install matplotlib with conda install, reinstall pymodaq manually with "python setup.py install" but it can't help.

conda list gives:
..., pyqt 5.6.0, PyQt5 5.13.0, ...

regards,

loon

**Comment by seb5g** [comment]
Use a console to start a given script so that you may have an idea of what packages are missing. So activate your env. Then type.: python pymodaq.daq_scan.daq_scan_main and let me know what 's returned?

**Comment by looninho** [comment]
Hi seb5g,

So I did your instruction but get:

```
(DAQ) D:\git\PyMoDAQ\pymodaq\examples>python pymodaq.daq_scan.daq_scan_main
python: can't open file 'pymodaq.daq_scan.daq_scan_main': [Errno 2] No such file or directory
```

I can execute the 'custom_app.py' file but get import errors:
\```
PyMoDAQ\pymodaq\examples>python custom_app.py
error while trying to import module daq_0Dviewer_NIDAQmx:Location of niDAQmx library and include file unknown on win32 - if you find out, please let the PyDAQmx project know
error while trying to import module daq_1Dviewer_NIDAQmx:Location of niDAQmx library and include file unknown on win32 - if you find out, please let the PyDAQmx project know
error while trying to import module daq_2Dviewer_FLIM:No module named 'serial.tools'
error while trying to import module daq_2Dviewer_OrsaySTEM:[WinError 126] Le module spécifié est introuvable
error while trying to import module daq_2Dviewer_TIS:No module named 'pyicic'
error while trying to import module daq_move_Conex:No module named 'serial.tools'
error while trying to import module daq_move_Holoeye:No module named 'holoeye'
error while trying to import module daq_move_OrsaySTEM:[WinError 126] Le module spécifié est introuvable
error while trying to import module daq_move_PI:No module named 'pipython'
error while trying to import module daq_move_PiezoConcept:No module named 'serial.tools'
error while trying to import module daq_move_SmarActMCS:[WinError 126] Le module spécifié est introuvable

```

**Comment by seb5g** [comment]
You have to add the option -m after the python command. python -m
pymodaq.daq_scan.daq_scan_main

All this is clearly written in the online help, please have a look.

The import error just shoes which plugin cannot work at the moment. Your
installation is lacking some specific packages, however pymodaq is fully
functional.

**Comment by looninho** [comment]
Hi seb5g,

I'm sorry for my carelessness in reading the doc. Now I put the -m option and get these error:

`(DAQ) C:\Users\ln>python -m pymodaq.daq_scan.daq_scan_main
error while trying to import module daq_move_Conex:No module named 'serial.tools'
error while trying to import module daq_move_Holoeye:No module named 'holoeye'
error while trying to import module daq_move_OrsaySTEM:[WinError 126] Le module spécifié est introuvable
error while trying to import module daq_move_PI:No module named 'pipython'
error while trying to import module daq_move_PiezoConcept:No module named 'serial.tools'
error while trying to import module daq_move_SmarActMCS:[WinError 126] Le module spécifié est introuvable
error while trying to import module daq_0Dviewer_NIDAQmx:Location of niDAQmx library and include file unknown on win32 - if you find out, please let the PyDAQmx project know
error while trying to import module daq_1Dviewer_NIDAQmx:Location of niDAQmx library and include file unknown on win32 - if you find out, please let the PyDAQmx project know
error while trying to import module daq_2Dviewer_FLIM:No module named 'serial.tools'
error while trying to import module daq_2Dviewer_OrsaySTEM:[WinError 126] Le module spécifié est introuvable
error while trying to import module daq_2Dviewer_TIS:No module named 'pyicic'
No module named 'pymodaq_pid_models'
Traceback (most recent call last):
  File "C:\Users\ln\AppData\Local\Continuum\Anaconda3\envs\DAQ\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\ln\AppData\Local\Continuum\Anaconda3\envs\DAQ\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\ln\AppData\Local\Continuum\Anaconda3\envs\DAQ\lib\site-packages\pymodaq\daq_scan\daq_scan_main.py", line 7, in <module>
    from pymodaq.daq_utils.pid.pid_controller import DAQ_PID
  File "C:\Users\ln\AppData\Local\Continuum\Anaconda3\envs\DAQ\lib\site-packages\pymodaq\daq_utils\pid\pid_controller.py", line 12, in <module>
    from pymodaq.daq_utils.manage_preset import PresetManager
  File "C:\Users\ln\AppData\Local\Continuum\Anaconda3\envs\DAQ\lib\site-packages\pymodaq\daq_utils\manage_preset.py", line 18, in <module>
    from pymodaq.daq_utils.pid.pid_params import params as pid_params
  File "C:\Users\ln\AppData\Local\Continuum\Anaconda3\envs\DAQ\lib\site-packages\pymodaq\daq_utils\pid\pid_params.py", line 28, in <module>
    raise Exception('No valid installed models')
Exception: No valid installed models`

So I try to import one by one the modules in daq_scan_main.py, only these lines give error:

`from pymodaq.daq_utils.pid.pid_controller import DAQ_PID
from pymodaq.daq_utils.manage_preset import PresetManager
`
and also this in another dependant file:

`from pymodaq.daq_utils.pid.pid_params import params as pid_params
`
regards,

Antoine

**Comment by seb5g** [comment]
I see,
the missing stuff are related with a new feature of PID. You need to
install this specific package:
https://pypi.org/project/pymodaq-pid-models/

then it should be all fine, well let me know!!


Sébastien Weber
*Président AbsoluRaid*
*seba.weber@gmail.com <seba.weber@gmail.com>*

*www.absoluraid.com <http://www.absoluraid.com>*

**Comment by seb5g** [comment]
Actually i've added a patch version 1.5.1 to install it together with pymodaq. Thanks for your testing!!

**Comment by looninho** [comment]
I reinstall with the new 1.5.1 version but still missing holoeye, daq_move_OrsaySTEM and pipython.

After I installed pyserial, serial.tools issue is solved.

conda list has pymodaq 1.5.1, pymodaq-pid-models 0.0.1, pymodaq-plugins 1.1.3.

seems that the path to these modules missing in my system...

regards,

loon

**Comment by seb5g** [comment]
Hello again,
to be clear:
the message you got are just warnings to tell you something is missing on
your computer to run properly some plugins. For instance to run the Holoeye
one, you would need the corresponding dll from the manufacturer. Because
you don't have it on your computer, the package cannot load properly, it
tells you that and then you don't see it in the list of available plugins.

Same for Orsay and pipython that is delivered by Physik Instrumente...hope
its clear now?

**Comment by looninho** [comment]
Thank you Sébastien, for your wonderful work!

PyMoDAQ works now, just a bug to fix:

I rename the 'DAQ_Measurement_main.py' filename by 'daq_measurement_main.py' because I have this error msg:

> File "C:\Users\ln\AppData\Local\Continuum\anaconda3\envs\DAQ\lib\site-packages\pymodaq-1.5.1-py3.7.egg\pymodaq\daq_utils\plotting\viewer1D\viewer1D_main.py", line 5, in <module>
    from pymodaq.daq_measurement.daq_measurement_main import DAQ_Measurement
ModuleNotFoundError: No module named 'pymodaq.daq_measurement.daq_measurement_main'

Now I have to write my plugins for some massflow, temperature sensor, etc.

regrads,

loon

**Comment by seb5g** [comment]
Thanks, which lab are you from?
Seb

**Comment by looninho** [comment]
Hi,
I'm from CRHEA on the Côte d'Azur ;)
Loon
