### ISSUE TITLE
Git structure

### ISSUE THREAD

**Issue by ddennetiere** [CEMES-CNRS/PyMoDAQ#35]
When installing with pip, the content of the repo is put in python/Lib/site-packages which for example install the "test" folder in site-packages also.
It also prevent the user from syncing with git, say going in site packages and git init, then git remote add origin. That would prevent any push down the road.
Finally, the documentation only states one method of installing pip, but I have come to understand that git would be a preferred method ? Should it be included in the docs ?

David

**Comment by seb5g** [comment]
You're completely right. I'm just working on this moving the source file within a src  folder in the git repo. I'm also working on using tox and continuous integration

**Comment by seb5g** [comment]
Concerning your second point:
Git should not really be used directly except for plugins as not everyone can publish packages while its fairly easy to produce source distributions in github. However it is indeed true that pymodaq can be installed from github, do you want to work on the docs to include this?

**Comment by ddennetiere** [comment]
That's totally up to you ! depends on how you want your users to interact with the code !
Maybe a git link should appear somewhere in the installing part of the doc if only for reference.
But when you say plugins should be installed through git : you doc doesn't mention that and only mentions the plugin manager...

**Comment by seb5g** [comment]
Yes sorry, the plugin manager is fetching plugins from the source distributions located on github (or elsewhere). That's why I was mentioning installation from git

**Comment by seb5g** [comment]
The package layout has been rewritten following the src layout, that means packaging and installed python module are separated. Finally the source files can be obtained using pip from pypi or from the github repo. Last, Continuous integration has been configured to track bugs in commits. However the test suite is still very thin and must be extended. Calling for help here!!
