### ISSUE TITLE
Mock_spectro bug

### ISSUE THREAD

**Issue by ddennetiere** [CEMES-CNRS/PyMoDAQ#38]
Hi Seb, 
the mock_spectro plugin has a bug and a weird behavior (which may be intentional).

The bug is line 250 : the msleep time from the parameters must be cast as an int.

The behavior is that when you load the detector, it provides a signal which is nothing but noise, you have to uninitialize it and initialize it for it to work. As I said, it may be intentional, so if it is, you're welcome to ignore this part of the issue.

**Comment by seb5g** [comment]
This issue should be raised in the pymodaq_plugins repository. I will therefore close this one here and open the same one on the repo (and reply to it ;-) )
