### ISSUE TITLE
Plugin manager (pymodaq 2.3.2)

### ISSUE THREAD

**Issue by quantumm** [CEMES-CNRS/PyMoDAQ#40]

**Comment by quantumm** [comment]
It seems like in daq_utils.get_plugins importlib.import_module raise an exception if it deals with non-default plugins.

**Comment by quantumm** [comment]
Seems that the last commit did the job thanks ;)

**Comment by seb5g** [comment]
Yes I checked it yesterday, it was related to 2 bugs:
one related to a feature now included in the standard library (from py3.8 onwards) to discover plugins
the other one was de to the new src layout of the repository and the fact the VERSION file was not copied when installing the package. So so far only the latest code from github will work. I will plan a release as soon as I checked/cleaned all my plugin repos.
