### ISSUE TITLE
TCPClient

### ISSUE THREAD

**Issue by quantumm** [CEMES-CNRS/PyMoDAQ#45]
Hi,
I tested the TCP client but got an error due to the call (lign 472)

`self.cmd_signal.emit(ThreadCommand('get_axis'))`

This call a method get_axis on a viewer plugin but it is not in the template.
I do not know what it is supposed to do but if I comment this lign things seems to work fine !

**Comment by seb5g** [comment]
that was a tricky one, I used mostly TCPclient for daqViewer but it seems you used it for a move. This get_axis command is specific to DAQViewers, I therefore modified the code with the possibility to add extra cmmands at initialization of the tcp client, and moved the get_axis one within the daq_viewer itself. Could you try it on the last github version please?
Cheers

**Comment by seb5g** [comment]
@quantumm could you close the issue if the patch is ok?

**Comment by quantumm** [comment]
Sorry it did not have time to test it and i am on holidays now. But i do not forgot about it ;)

**Comment by seb5g** [comment]
and now?

**Comment by quantumm** [comment]
Hi !

I tested again the TCP communication with both computers with pymodaq 3.1.2.
I have a new problem since for now I cannot get the communication between the two computers at all.
Here is the procedure I followed :

* start a daq_viewer on the server computer. Select DAQ1D->TCPServer and click Ini. Det. with port 6341 and IP localhost in Detector settings. By the way now the default IP is 10.47.0.39 I guest this should be corrected.
* start a daq_viewer on the client computer. Select DAQ1D->Mock and start grab.
* In Main settings / TCP/IP options put the IP address of the server computer and port 6341.

When i click Connect nothing happens and in the log i have this error:

2021-07-12 10:53:36,737 - pymodaq.pymodaq.daq_viewer_main.Testing - INFO -   File "c:\users\attose1_vmi\appdata\local\continuum\anaconda3\envs\tmp_test_tcp\lib\site-packages\pymodaq\daq_utils\tcp_server_client.py", line 467, in init_connection
    self.socket.connect((self.ipaddress, self.port))
  File "c:\users\attose1_vmi\appdata\local\continuum\anaconda3\envs\tmp_test_tcp\lib\site-packages\pymodaq\daq_utils\tcp_server_client.py", line 58, in connect
    return self.socket.connect(*args, **kwargs)
**[WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusées**

Maybe this could be due to the local network. Something with firewall ? But at the time of my previous test i used the same network and it was working... For now I do not know i have to dig into it. So there is a chance it has nothing to do with pymodaq.

If you have any experience with this kind of error please tell me ;)

**Comment by seb5g** [comment]
If you use TCP/IP connection on different computers, you should **not** use *localhost* as the connection would not be made from external computers. You then have to replace the IP with the one of your server. You can set the default IP in the configuration file:
![image](https://user-images.githubusercontent.com/6609955/125297544-9b14e680-e327-11eb-8bc1-9b0d1f3f6ba6.png)
let me know

**Comment by quantumm** [comment]
Yes you were right ! ;)
The IP on the server side should be its own IP. I do not know why I put localhost…
Thanks a lot !
