### ISSUE TITLE
Scanner settings in daq_scan

### ISSUE THREAD

**Issue by quantumm** [CEMES-CNRS/PyMoDAQ#48]
It happens that if I define some (quite demanding !) parameters in a daq_scan, then python will crash and there will be nothing in the logs.
For exemple if I define a very long scan with tiny steps : start 1, stop 2000, step 0.01.

**Comment by NPy2020** [comment]
I Have the same thing when I forget to change the step. I need to wait some minutes to see that I select 80 000 points.
In your case, PyMoDAQ build the place to follow 200 000 points !!
You can try to just wait few minutes to see the result.

For me now I always change the step in first and the start and stop after, to pass the state where PyMoDAQ take time to calculate to much points.

**Comment by seb5g** [comment]
I don't know how to overcome this except by phyically limiting the values to a given number of points (say 1000) but if at some point one want to do a scan with 1001... This limit could also be in the config file, so that a user can change it... what do you think?

**Comment by NPy2020** [comment]
Yes I agree with the limit you can change in the config file. In this case it become a bounds parameter adapted to your experiment.

**Comment by seb5g** [comment]
could you close this issue if it is fixed?
