### ISSUE TITLE
HDF5 save data address

### ISSUE THREAD

**Issue by NPy2020** [CEMES-CNRS/PyMoDAQ#49]
Hello,

The general name of the data saving file with date and dataset number is nice to access it but I find that the address is little longer.
I mean one repository for one day experiment could be enough to contain all dataset of the day.
The repository with exactly the same name of the dataset is to much for me.

What do you think about that ?

**Comment by seb5g** [comment]
I agree, this was so from older saving mechanisms when other files where saved together with the h5 one. Commit 628ed3930220feeeaa23d1ec855bf7c9d32d044f is fixing this removing the redondant foler
