### ISSUE TITLE
identification Ax1 and Ax2, 2D acquisition

### ISSUE THREAD

**Issue by NPy2020** [CEMES-CNRS/PyMoDAQ#50]
Hi,

In 2D scan, with two actuators I find that is difficult to remember  which we select Ax1 and Ax2 to write start, stop and step values without mistake. because of only select Ax1 and Ax2 by clicking first and second.
![image](https://user-images.githubusercontent.com/83576939/116857050-73552400-abfc-11eb-9e1c-f8bd0d272ab4.png)

Is it possible to add small information link to the selection of these actuators, on "Ax1" and "Ax2" to remember during experiment who's who ?

**Comment by seb5g** [comment]
Commit 628ed3930220feeeaa23d1ec855bf7c9d32d044f is adding a tooltip to values of each axis depending on the actuator selection:
![image](https://user-images.githubusercontent.com/6609955/116868884-e7e58e00-ac0f-11eb-9f97-6ce30dff1a9b.png)
