### ISSUE TITLE
How configuration file is working ?

### ISSUE THREAD

**Issue by NPy2020** [CEMES-CNRS/PyMoDAQ#53]
Hi,

I would like to use the configuration file to use directly the DAQ_scan pass on the dashboard step.

Actually I must  : 1-open dashboard / 2-select good preset - wait / 3-select "do scan"
even I written in the config file the good preset and parameter of scan.
What i need to do to make that when I open PyMoDAQ i have directly the scan windows with the configuration file parameter's ?
is it in the windows shortcut actually target on dashboard ?

thanks

**Comment by seb5g** [comment]
If the config file is correctly set with the correct preset file name. You can start directly the daq_scan module and it will itself do your steps 1, 2 and 3 !

**Comment by seb5g** [comment]
@NPy2020 try the last commit https://github.com/CEMES-CNRS/PyMoDAQ/commit/1a715cfc0e21eead5c615defe38820e5d31119af

![image](https://user-images.githubusercontent.com/6609955/117875974-16640880-b2a3-11eb-9e4b-a81e6666129d.png)

delete your current local config file before trying so that python copy the adequate template containing the configs for time_flow

**Comment by NPy2020** [comment]
I have modifie this few line in the "config_template" file. I see now the parameters in the config file. Thanks.
But ...
the first time daq-scan opened without the value of the time flow in config file I have write.
and now daq_scan don't want to opened himself ! I see dashboard opening and plugin charging but at the end of these init it close all and i have this error :
![image](https://user-images.githubusercontent.com/83576939/117954278-287f8e80-b317-11eb-8981-f6515981f588.png)

I try to suppress config_file.toml and create a new. It happened the same thing.

**Comment by seb5g** [comment]
You have to download and install the new source from github to test it.
Don't touch the template and delete your local file.  A new local file will
be created.  The error you're seeing seems to come from the values of stay
stop step. .

**Comment by NPy2020** [comment]
Thanks,
It's working now.
