### ISSUE TITLE
Inconsistent license specification

### ISSUE THREAD

**Issue by davidtrem** [CEMES-CNRS/PyMoDAQ#7]
There is an inconsistent license specification on the github repo, the documentation
http://pymodaq.cnrs.fr/ and setup.py file. The last two specify a MIT licensing while
on github repo one can read GPLv3 (screen capture below)
there also an GPL LICENSE file  (https://github.com/CEMES-CNRS/PyMoDAQ/blob/master/LICENSE)
![Capture d’écran_2019-09-20_14-49-14](https://user-images.githubusercontent.com/277579/65328275-3880b280-dbb6-11e9-893e-077908cbfd48.png)

**Comment by davidtrem** [comment]
This doc might help : https://help.github.com/en/articles/adding-a-license-to-a-repository

**Comment by seb5g** [comment]
Choose to publish this code now as a CECILL-B License  https://cecill.info/
