### ISSUE TITLE
installing plugins from source

### ISSUE THREAD

**Issue by LMSC-NTappy** [CEMES-CNRS/PyMoDAQ#71]
Hello,

I am trying to install a plugin from source (thorlabs) and after running the famous `pip install -e .`  command I am not able to find it in the daq_viewer or the plugin_manager... 
What am I missing?  The only information I am able to find in the documentation is http://pymodaq.cnrs.fr/en/latest/usage/modules/Plugins.html#how-to-contribute

Many thanks in advance,

Nicolas

EDIT: Could it be that it works only if PyMoDAQ is installed from source as well? I'll try this first

**Comment by LMSC-NTappy** [comment]
Ok, it turns out that to make it work, PyMoDAQ must also be installed from source and located in the same directory as the plugins repository. 

Any idea what that is? In my opinion the use case where pymodaq is installed from pypi (prod version) and plugins are installed in edit mode by users is the most common and should work, however I have no idea how to make it work.

How about adding a note in the documentation explaining how to make it work as a first step?

**Comment by seb5g** [comment]
PyMoDAQ and its plugins are all different python packages. That means they can either be installed from source or from pypi independently. The only restriction is of course that all have to be in the same environment. 

Now that this is said, your issue can come from the fact that the source code is more recent than the pypi one, there could therefore be some bugs in it or at least something that make it unseen from pymodaq. My first guess is that the source code for thorlabs is maybe needing something that is not in the pypi version...

Finally could you tell what instrument you are looking for in the thorlabs plugin?

**Comment by LMSC-NTappy** [comment]
>PyMoDAQ and its plugins are all different python packages. That means they can either be installed from source or from pypi independently. The only restriction is of course that all have to be in the same environment.
I am well aware of that, I was thinking maybe it was related to how pymodaq detects the installed plugins...

>Now that this is said, your issue can come from the fact that the source code is more recent than the pypi one, there could therefore be some bugs in it or at least something that make it unseen from pymodaq. My first guess is that the source code for thorlabs is maybe needing something that is not in the pypi version...
That's a good point, I could try once more and pay closer attention to the logs but I could find a fix to this solution

>Finally could you tell what instrument you are looking for in the thorlabs plugin?
Currently, a DCC1545M (obsolete in the thorlabs magazine) sensor but we have also some flip mirror, rotation mounts and led drivers (all Kinesis) that we'd like to control. I could make it work for the camera now, haven't tested the other optomech.

Related posts for the anyone's interest:
CEMES-CNRS/pymodaq_plugins_thorlabs#5
mabuchilab/Instrumental#144
mabuchilab/Instrumental#150

If you agree I think this issue can be closed now
