### ISSUE TITLE
Correct way to change between 1D and 2D viewer

### ISSUE THREAD

**Issue by LMSC-NTappy** [CEMES-CNRS/PyMoDAQ#73]
Hello,

I am working on a plugin capable of handling Princeton Instruments Cameras. 

So far everything works nicely but I just don't get how I should make the module capable of switching between 1D and 2D viewers depending on wether the camera is binned along one axis or not. 

Is there a way to do it? Should I initialize both at the connection with the detector? If you could just give me some general indications to get me started it would be really appreciated.

Best Regards

Nico

**Comment by LMSC-NTappy** [comment]
Many thanks for your reply, I'll take a look and give it a try!

**Comment by seb5g** [comment]
Do you think you could write your driver within the instrumental package.
It's quite nice for c based library. And I will produce soon a way to
quickly use instrumental instruments within pymodaq in a generic way. For
recent exemple of how to write instrumental driver I added in my fork
smaract scu driver and thorlabs tlpm powermeter!


Le mar. 29 mars 2022 à 14:57, Nicolas Tappy ***@***.***> a
écrit :

**Comment by LMSC-NTappy** [comment]
I am sorry I already have it fully implemented using pylablib (which I recommend you check out, it's awesome!), the only missing feature is switching between 1D and 2D data!

Cheers

Nico

**Comment by LMSC-NTappy** [comment]
Thanks @rgeneaux , what you suggested did the job alright!

I run into a benine deprecation warnings when the software changes between Data1D and Data2D :
```
2022-03-31 15:00:09,865 - py.warnings - WARNING - c:\users\admin\documents\pymodaq_dev\pymodaq\src\pymodaq\daq_utils\parameter\pymodaq_ptypes\table.py:110: DeprecationWarning: Deprecated Qt API, will be removed in 0.13.0.
  w.horizontalHeader().setResizeMode(QtWidgets.QHeaderView.Stretch)
```

Just wondering: would there be an advantage to implement it as an asynchronous plugin? 

FYI, you can check it out here:
https://github.com/LMSC-NTappy/pymodaq_plugins_princeton_instruments

I don't recommend integration in the pmodaq repo yet, because for now it relies on a pylablib version that is unreleased but sometimes next week pylablib should be updated.

I'll give you heads up

Cheers

Nico

**Comment by seb5g** [comment]
What do you mean asynchronous? Like with no blocking methods as suggested
in the doc?


Le jeu. 31 mars 2022 à 17:15, Nicolas Tappy ***@***.***> a
écrit :

**Comment by LMSC-NTappy** [comment]
Yes, exactly.

I know that it's blocking the plugin while the grab_data method operates, I am fine with that. What I wonder is if we can do more interaction with the detector while it's acquiring in asynchronous mode (e.g. changing the integration time without stopping and restarting the acquisition).

**Comment by seb5g** [comment]
Well
I made several examples of plugins using the async mode. The simplest is
the daqmx one. The idea is always to register a callback that will be
called when data is ready. For camera and live grabbing it's a bit trickier
but the andor camera plugins are using this mechanism

In principle, you can apply mods of the settings during the acquisition if
you driver is letting you and if your plugin is written for this. For
instance, changing the exposure should be fine, but changing the size of
the image should be tricky as you need to prepare buffers of the correct
size...

Sébastien



Le jeu. 31 mars 2022 à 18:37, Nicolas Tappy ***@***.***> a
écrit :

**Comment by rgeneaux** [comment]
I was wondering the same thing as @LMSC-NTappy, as the Greateyes CCD library has methods for both sync/async (they call it blocking/non blocking) functionalities. I ended up only implementing the async one by following the way you did the andor plugin. 

But I did wonder : in terms of "user experience", do you know what difference there will be between a sync or async grab_data method? Will the interface be more responsive between the acquisition of frames? Perhaps we gain something on maximum FPS? 

All this is not critical to what we use PyMoDAQ for yet, but as we try to acquire larger data flows, and at higher acquisition rates, they might matter someday!

**Comment by seb5g** [comment]
Well the simplest example is to be able to stop the grab while doing a long
acquisition for instance. A blocking grab will stop only after... so indeed
it will be more responsive. For the fast frame rate and so on, I'm thinking
a dedicated plugin should be used, that will plot only images from time to
time and will have a direct saving mechanism to a custom h5 file within the
plugin (well in another thread run from the plugin).

Did something like this for photon time tagged counting at high rate in the
pymodaq_plugin_flim:

**Comment by LMSC-NTappy** [comment]
> In principle, you can apply modifications of the settings during the acquisition if
you driver is letting you and if your plugin is written for this. For
instance, changing the exposure should be fine, but changing the size of
the image should be tricky as you need to prepare buffers of the correct
size...

I see. That's nice because picam lets you know which setting can be modified online and which does not.

> Well the simplest example is to be able to stop the grab while doing a long
> acquisition for instance. A blocking grab will stop only after... so indeed
> it will be more responsive.

Definitely very useful! 

I will give it a try then. It sounds very useful indeed

**Comment by LMSC-NTappy** [comment]
Well, in the end it was more easy to implement than I had anticipated. I recommend you give it a try too @rgeneaux  :)

I cannot change the parameters during acquisition though, but that's a library issue. There are special methods to do it and even though they are wrapped in pylablib, the camera control interface does not use it. I can probably do it with explicit library calls but for now it's just not worth it.

Many thanks for the help, the plugin is now quite solid I think!

I'll notify you when the new release of pylablib is out.
