### ISSUE TITLE
skipping the dashboard

### ISSUE THREAD

**Issue by ddennetiere** [CEMES-CNRS/PyMoDAQ#75]
So say I've a working project, meaning a preset with actuators and detectors.

Is there a way to run that preset directly or do we have to go through the dashboard, unroll the preset menu, unroll the loadable presets and finally lauch our preset ?

In other terms, is it possible to skip the dashboard ?

**Comment by ddennetiere** [comment]
I have read issue #53 but it seems that the config file only handles daq_scan and daq_logger configurations

**Comment by seb5g** [comment]
Very easy to tackle. You may want to look at the main function in the daq_scan module that shows how the dashboard is automatically loaded depending on the preset in the config. In short, you have to create a script you will run where there is this code:
```
if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    from pymodaq.dashboard import DashBoard
    win = QtWidgets.QMainWindow()
    area = pymodaq.daq_utils.gui_utils.dock.DockArea()
    win.setCentralWidget(area)
    win.resize(1000, 500)
    win.setWindowTitle('PyMoDAQ Dashboard')

    dashboard = DashBoard(area)
    file = Path(get_set_preset_path()).joinpath(f"{config('presets', 'the_name_of_your_preset')}.xml")
    if file.exists():
        dashboard.set_preset_mode(file)
    else:
        msgBox = QtWidgets.QMessageBox()
        msgBox.setText(f"The default file specified in the configuration file does not exists!\n"
                       f"{file}\n"
                       f"Impossible to load the DAQ_Scan Module")
        msgBox.setStandardButtons(msgBox.Ok)
        ret = msgBox.exec()

    sys.exit(app.exec_())
```

**Comment by LMSC-NTappy** [comment]
What about adding an option as an optional argument to the command line? 

I imagine something like `dashboard -p custom_preset.xml` or `dashboard --preset custom_preset.xml` 

If you're open to a PR I would give a shot to implement it based on your snippet

**Comment by ddennetiere** [comment]
that would be fine !

**Comment by seb5g** [comment]
There is no CLI implemented so if we start adding arguments we will need to
make a specific doc for it. Is it worth it?


Le mer. 6 avr. 2022 à 15:38, Nicolas Tappy ***@***.***> a
écrit :

**Comment by LMSC-NTappy** [comment]
> There is no CLI implemented so if we start adding arguments we will need to
make a specific doc for it. Is it worth it?

I guess it's more hassle than gain if a custom launcher is easy to do...

**Comment by ddennetiere** [comment]
Yes,the lancher is more than sufficient.

One precision though : don't forget to add your preset to the config file : 

here's my launcher : 


```
from pymodaq.dashboard import DashBoard
from PyQt5 import QtWidgets
import pymodaq
from pathlib import Path
import sys
from pymodaq.daq_utils.config import Config, get_set_preset_path


if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    win = QtWidgets.QMainWindow()
    area = pymodaq.daq_utils.gui_utils.DockArea()
    win.setCentralWidget(area)
    win.resize(1000, 500)
    win.setWindowTitle('PyMoDAQ Dashboard')
    config = Config()
    dashboard = DashBoard(area)
    file = Path(get_set_preset_path()).joinpath(f"{config('presets', '<name of my preset>')}.xml")
    print(file)
    if file.exists():
        dashboard.set_preset_mode(file)
    else:
        msgBox = QtWidgets.QMessageBox()
        msgBox.setText(f"The default file specified in the configuration file does not exists!\n"
                       f"{file}\n"
                       f"Impossible to load the DAQ_Scan Module")
        msgBox.setStandardButtons(msgBox.Ok)
        ret = msgBox.exec()

    sys.exit(app.exec_())
```

And in my config_template.toml I've added in presets : 

```
[...]
[presets]
default_preset_for_scan = "preset_default"
default_preset_for_logger = "preset_default"
<name of my preset> = "<name of the preset XML file>"
[...]
```

I'll close the issue.
